app/models.py
# 用户模型
# 查看用户处于啥状态
from flask_login import UserMixin
# 加密方案
from werkzeug.security import generate_password_hash, check_password_hash

from app.extentions import db, login_manager


class User(db.Model, UserMixin):
    id = db.Column(db.Integer, primary_key=True)
    username = db.Column(db.String(50), unique=True)
    password_hash = db.Column(db.String(150))
    emil = db.Column(db.String(50), unique=True)
    cinfirmed = db.Column(db.Boolean, default=False)

    @property
    def password(self):
        raise AttributeError('密码不告诉你')

    #     加密存储密码
    @password.setter
    def password(self, password):
        self.password_hash = generate_password_hash(password)

    #     密码校验
    def verify_password(self, password):
        return check_password_hash(self.password_hash, password)




# 回到函数
# 根据用户id找到用户对象
@login_manager.user_loader
def load_user(uid):
    return User.query.get(uid)

app/forms.py
from flask_wtf import FlaskForm
from wtforms import StringField, PasswordField, SubmitField, BooleanField
from wtforms.validators import Length, EqualTo, Email, ValidationError, DataRequired

from .models import User


# 注册表单
class Register(FlaskForm):
    username = StringField('用户名:', validators=[Length(6, 12, message='用户名必为6到12个字符长度的字符串')])
    password = PasswordField('密码:', validators=[Length(3, 12, message='密码必须为3到12个字符长度')])
    confirm = PasswordField('确认密码:', validators=[EqualTo('password', message='密码不一致')])
    email = StringField('邮箱:', validators=[Email(message='邮箱格式不正确')])
    submit = SubmitField('马上注册')
    #     o自定义验证
    def validate_username(self, field):
        # 自定义验证username
        if User.query.filter(User.username == field.data).first():
            raise ValidationError('用户已经存在，请使用其他用户名！')
        # 自定义验证emai
    def validate_email(self, field):
        if User.query.filter(User.emil == field.data).first():
            raise ValidationError('该邮箱已经注册！')


# 登陆表单
class login_form(FlaskForm):
    username = StringField('用户名:', validators=[DataRequired(message='请填入用户名')])
    password = PasswordField('密码:', validators=[DataRequired(message='请填入密码')])
    remember = BooleanField('记住我？')
    submit = SubmitField('登陆')

app/__init__.py
# 创建实例
from flask import Flask

from app.config import config
from app.extentions import init_extension
from app.views import register_blueprint


def creat_app(config_name):
    app = Flask(__name__)
    # 初始化配置
    if config_name not in config:
        config_name = 'develop'
    app.config.from_object(config[config_name])
    # 初始化函数调用
    init_extension(app)
    # 注册蓝图
    register_blueprint(app)
    return app

app/views/__init__.py
# 封装注册蓝图函数
from .main import main
from .posts import posts
from .user import user

# 蓝图
BEFAULT_BLUEPRINT = (
    (main, ''),
    (user, '/user'),
    (posts, '/posts')
)

def register_blueprint(app):
    for blue_name, prefix in BEFAULT_BLUEPRINT:
        app.register_blueprint(blue_name, url_prefix=prefix)

app/views/main.py
from flask import Blueprint, render_template
main = Blueprint('main', __name__)


@main.route('/')
def index():
    return render_template('main/index.html')

app/views/posts.py
from flask import Blueprint

posts = Blueprint('posts', __name__)


@posts.route('/posts/')
def send_posts():
    return '回复成功'

app/views/user.py
from flask import Blueprint, render_template, flash, redirect, url_for, current_app, request
# login_user管理当前的用户, login_required登录保护页面
from flask_login import login_user, logout_user, login_required
from itsdangerous import JSONWebSignatureSerializer as Serializer

from app.email import send_mail
from app.extentions import db
from app.forms import Register, login_form
from app.models import User

user = Blueprint('user', __name__)


# 注册
@user.route('/register/', methods=['GET', 'POST'])
def register():
    form = Register()
    if form.validate_on_submit():
        # form.validate_email(form.email.data)
        # form.validate_username(form.username.data)
        # 根据表单数据 创建用户对象
        u = User(username=form.username.data,
                 password=form.password.data,
                 emil=form.email.data)
        # 把用户信息保存到数据库
        db.session.add(u)
        # 发送账户激活邮件
        # 标识身份数据
        s = Serializer(current_app.config['SECRET_KEY'])
        # 当前用户id为空，要手动提交
        db.session.commit()
        token = s.dumps({'id': u.id})
        send_mail('账户激活', u.emil, 'email/ectivate.html', username=u.username, token=token)
        flash('您已经注册成功，请点击邮件中链接进行激活！')
        return redirect(url_for('main.index'))
    return render_template('user/register.html', form=form)


# 激活
@user.route('/activate/<token>')
def activate(token):
    # 根据已有的元素和秘钥生成一个加密的令牌
    s = Serializer(current_app.config['SECRET_KEY'])
    try:
        data = s.loads(token)
    except:
        flash('激活失败')
        return redirect(url_for('main.index'))
    u = User.query.get(data['id'])
    if not u.cinfirmed:
        u.cinfirmed = True
        db.session.add(u)
    flash('激活成功！')
    return redirect(url_for('user.login'))



# 登陆
@user.route('/login/', methods=['GET', 'POST'])
def login():
    form = login_form()
    if form.validate_on_submit():
        u = User.query.filter(User.username == form.username.data).first()
        if not u:
            flash('无效用户')
        elif not u.cinfirmed:
            flash('账户未激活，请先激活')
        elif not u.verify_password(form.password.data):
            flash('密码错误')
        else:
            flash('登陆成功')
            # login_user该方法会直接使用户进入登录后的界面
            # remember参数是否记住我,默认为false
            login_user(u, remember=form.remember.data)
            # 登录后返回原网页
            return redirect(request.args.get('next') or url_for('main.index'))
    return render_template('user/login.html', form=form)


# 退出登录
@user.route('/logout/')
def logout():
    # 使用户从登录状态转为未登录状态
    logout_user()
    flash('已经成功退出登录!')
    return redirect(url_for('main.index'))


# 受保护的页面，登陆后才可以访问
@user.route('/test/')
# 保护指定的路由
@login_required
def test():
    return 'ddddd'

app/templates/comment/base.html
{# 继承自bootstrap基础模板 #}
{% extends 'bootstrap/base.html' %}

{% block title %}个人博客{% endblock %}

{% block content %}
    <div class="container">
        {% for message in get_flashed_messages() %}
            <div class="alert-warning alert-dismissable" role="alert">
                <button type="button" class="close" data-dismiss="alert"
                        aria-label="Close"><span aria-hidden="true">&times;</span>
                </button>
                {{ message }}
            </div>
        {% endfor %}

        {% block page_content %}默认内容{% endblock %}
    </div>
{% endblock %}
{#快速渲染表单宏#}
{% from 'bootstrap/wtf.html' import quick_form %}





{% block navbar %}
    <nav class="navbar navbar-inverse" style="border-radius: 0px;">
        <div class="container">
            <!-- Brand and toggle get grouped for better mobile display -->
            <div class="navbar-header">
                <button type="button" class="navbar-toggle collapsed" data-toggle="collapse"
                        data-target=".navbar-collapse" aria-expanded="false">
                    <span class="sr-only">Toggle navigation</span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                    <span class="icon-bar"></span>
                </button>
                <a class="navbar-brand" href="{{ url_for('main.index') }}">首页</a>
            </div>

            <!-- Collect the nav links, forms, and other content for toggling -->
            <div class="collapse navbar-collapse">
                <ul class="nav navbar-nav">
                    <li><a href="#">版块一</a></li>
                    <li><a href="#">版块二</a></li>
                </ul>
                <ul class="nav navbar-nav navbar-right">
                    {% if current_user.is_authenticated %}
                        <li><a href="{{ url_for('user.logout') }}">退出</a></li>
                        <li class="dropdown">
                            <a href="#" class="dropdown-toggle" data-toggle="dropdown" role="button"
                               aria-haspopup="true" aria-expanded="false">{{ current_user.username }} <span
                                    class="caret"></span></a>
                            <ul class="dropdown-menu">
                                <li><a href="#">用户详情信息</a></li>
                                <li><a href="#">用户密码设置</a></li>
                                <li><a href="#">用户邮箱设置</a></li>
                                <li><a href="#">用户头像设置</a></li>
                            </ul>
                        </li>
                    {% else %}
                        <li><a href="{{ url_for('user.login') }}">登录</a></li>
                        <li><a href="{{ url_for('user.register') }}">注册</a></li>
                    {% endif %}
                </ul>
            </div><!-- /.navbar-collapse -->
        </div><!-- /.container -->
    </nav>
{% endblock %}

{% block head %}
    {{ super() }}
    <link rel="icon" type="image/x-icon" href="{{ url_for('static', filename='favicon.ico') }}"/>
{% endblock %}

app/templates/main/index.html
{% extends 'comment/base.html' %}

{% block title %}
    首页
{% endblock %}

{% block page_content %}
    <div class="jumbotron">
        <h1 style="font-family: 华文行楷">欢迎访问！</h1>
        <p>
            <img src="static/img/base.png" class="img-responsive" alt="Responsive image">
        </p>
        <table class="table table-hover">
            <tr>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
            </tr>
            <tr>
                <td></td>
                <td></td>
                <td></td>
            </tr>
        </table>
    </div>
{% endblock %}

app/templates/user/login.html
{% extends 'comment/base.html' %}

{% block title %}
    登陆
{% endblock %}

{% block page_content %}
    {{ quick_form(form) }}
{% endblock %}

app/templates/user/register.html
{% extends 'comment/base.html' %}

{% block title %}
    注册
{% endblock %}


{% block page_content %}
    {{ quick_form(form) }}
{% endblock %}